language: generic
sudo: false
before_install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - evm install $EVM_EMACS --use --skip
env:
  - EVM_EMACS=emacs-24.3-travis
  - EVM_EMACS=emacs-24.4-travis
  - EVM_EMACS=emacs-24.5-travis
  - EVM_EMACS=emacs-25.1-travis
  - EVM_EMACS=emacs-25.2-travis
  - EVM_EMACS=emacs-25.3-travis
  - EVM_EMACS=emacs-26.1-travis
script:
  - git clone --depth 1 https://code.orgmode.org/bzg/org-mode.git
  - (cd org-mode && make autoloads)
  - emacs --version
  - emacs -q -no-site-file -no-init-file --eval "(add-to-list 'load-path \"./org-mode/lisp\")" --eval "(require 'org)" -batch -f batch-byte-compile ox-epub.el
  - rm ox-epub.elc
