

* ox-epub

This is a fork of the [[https://github.com/ofosos/ox-epub][ox-epub package by
Mark Meyer.]] It has been modified to allow exporting epubs split into multiple
chapters uding the function org-epub-export-with-chapters. This splits top-level
headings in your org file separate html files, which are chapters within the
epub.

Generate =.epub= files directly from OrgMode. This will export EPUB
version 2, which should give broad compatibility. It should also be
relatiely easy to convert the resulting =.epub= to a =.mobi= (Kindle).


*THIS IS A WORK IN PROGRESS* and has probably introduced bugs not present in trunk
ox-epub. It required refactoring some of the package's internal workings. Bug
reports and PRs are welcome, though this is not my day job so I probably won't
be quick to respond.

** Prerequisites

This depends on Emacs 24.4 and OrgMode 9, it won't work on OrgMode 8 or
any version of Emacs before 24.4.

You will also need a working version of the =zip= utility.

** Installation

If you have MELPA stable activated, it is as simple as this:

=M-x package-install RET ox-epub RET=

** Usage

See the =sample= directory for a sample of what ox-epub can do.

Hit =C-c C-e E e= to publish the current buffer to an EPUB.

There are some required export options that need to be set. These are

 - =UID= a unique id of the document, otherwise known as uri, may be a url
 - =DATE= the date of the document, for valid values see
   [[https://www.w3.org/TR/NOTE-datetime]]
 - =AUTHOR= the document author or editor, the creator in the EPUB spec
 - =TITLE= the document title

Furthermore there are some properties which are optional:

 - =Subject= the subject matter of the book
 - =Description= a description of the book
 - =Publisher= the publisher of the book
 - =License= the rights associated with this book, the copyright
   notice and further rights may be included in this option.
 - =EPUBCOVER= the cover image to use for the export
 - =EPUBSTYLE= the CSS file to use for the export, this is set by default
   but can be set on a per document basis

The only other option that is exported:

 - =LANGUAGE= the language of the book, this is to be interpreted
   according to RFC3066 or it's succeeding documents
   [[https://www.ietf.org/rfc/rfc3066.txt]], no other interpretations are
   allowed according to the EPUB spec.

** Features

Currently =ox-epub= can do the following:

 - simple cover images
 - inclusion of png and jpg images
 - export of mathematical formulas
 - direct =.epub= generation
 - add stylesheets to your liking: Use the EPUBSTYLE property to add a
   list of stylesheets and customize =html-head-include-default-style=
   to toggle inclusion of the default stylesheet.

** Caveats

 - Mathematical formulas only export well if you use the =dvipng=
   backend. =dvipng= should be included in TeXlive.

** Coffee

I can't stand coffee. But feel free to give coffee money to Mark from his github.
